import React, { useEffect, useState } from 'react';
import { routes, sectionLabels } from '../config/routes.js';
import { requestJson } from '../services/api.js';
import { routeClick } from '../utils/navigation.js';
import { can } from '../utils/permissions.js';

/** Panel privado de administracion: roles, contenido, capturas y sincronizacion UEX. */
export function AdminPage({ currentUser, navigate }) {
  const [adminState, setAdminState] = useState({ roles: [], users: [], content: [], images: [] });
  const [status, setStatus] = useState('Cargando administracion...');
  const [busy, setBusy] = useState('');
  useEffect(() => { if (!currentUser) { setStatus('Necesitas iniciar sesion.'); return; } if (!can(currentUser, 'admin.access')) { setStatus('Tu rol no tiene acceso a administracion.'); return; } loadAdminState(); }, [currentUser?.id]);
  async function loadAdminState() { try { setAdminState(await requestJson('/api/admin/state')); setStatus('Panel listo.'); } catch (error) { setStatus(error.message); } }
  async function updateRole(userId, role) { setBusy(userId); try { setAdminState(await requestJson('/api/admin/users/' + encodeURIComponent(userId) + '/role', { method: 'PATCH', body: JSON.stringify({ role }) })); setStatus('Rol actualizado.'); } catch (error) { setStatus(error.message); } finally { setBusy(''); } }
  async function deleteContent(contentId) { setBusy(contentId); try { setAdminState(await requestJson('/api/admin/content/' + encodeURIComponent(contentId), { method: 'DELETE' })); setStatus('Publicacion eliminada.'); } catch (error) { setStatus(error.message); } finally { setBusy(''); } }
  async function deleteImage(imageId) { setBusy('image-' + imageId); try { setAdminState(await requestJson('/api/admin/images/' + imageId, { method: 'DELETE' })); setStatus('Captura eliminada.'); } catch (error) { setStatus(error.message); } finally { setBusy(''); } }
  async function syncVehicles() { setBusy('ships-sync'); setStatus('Sincronizando naves, precios y datos de combate...'); try { const payload = await requestJson('/api/vehicles/sync', { method: 'POST' }); setStatus('Catalogo sincronizado: ' + payload.count + ' naves.'); } catch (error) { setStatus(error.message); } finally { setBusy(''); } }
  if (!currentUser) return <main className="container single-column"><section className="auth-card panel"><h2>Administracion</h2><p className="auth-message">{status}</p><a className="action-btn primary-action" href={routes.login} onClick={(event) => routeClick(event, routes.login, navigate)}>Iniciar sesion</a></section></main>;
  return <main className="container admin-shell"><section className="admin-panel panel"><div className="panel-header"><div><span className="section-label">Permisos</span><h2>Control de administracion</h2></div>{can(currentUser, 'ships.sync') && <button className="action-btn primary-action" type="button" onClick={syncVehicles} disabled={busy === 'ships-sync'}>{busy === 'ships-sync' ? 'Sincronizando...' : 'Sincronizar UEX'}</button>}</div><p className="auth-message">{status}</p></section>{can(currentUser, 'users.manage') && <section className="admin-panel panel"><h3>Usuarios</h3><div className="admin-list">{adminState.users.map((user) => <article className="admin-row" key={user.id}><div><strong>{user.username}</strong><span>{user.email} · {user.provider} · Ultimo acceso: {user.lastLoginAt || 'N/D'}</span></div><select value={user.roleKey} onChange={(event) => updateRole(user.id, event.target.value)} disabled={busy === user.id}>{adminState.roles.map((role) => <option key={role.key} value={role.key}>{role.label}</option>)}</select></article>)}</div></section>}{can(currentUser, 'content.moderate') && <section className="admin-panel panel"><h3>Publicaciones</h3><div className="admin-list">{adminState.content.length ? adminState.content.map((item) => <article className="admin-row" key={item.id}><div><strong>{item.title}</strong><span>{sectionLabels[item.section] || item.section} · {item.author} · {item.createdAt}</span></div><button className="action-btn" type="button" onClick={() => deleteContent(item.id)} disabled={busy === item.id}>Eliminar</button></article>) : <p className="auth-message">No hay publicaciones.</p>}</div></section>}{can(currentUser, 'images.delete') && <section className="admin-panel panel"><h3>Capturas</h3><div className="admin-list">{adminState.images.length ? adminState.images.map((image) => <article className="admin-row" key={image.id}><div><strong>{image.name}</strong><span>{image.title}</span></div><button className="action-btn" type="button" onClick={() => deleteImage(image.id)} disabled={busy === 'image-' + image.id}>Eliminar</button></article>) : <p className="auth-message">No hay capturas.</p>}</div></section>}</main>;
}
