import React, { useEffect, useState } from 'react';
import { requestJson } from '../services/api.js';
import { money, meters, slugify, uniqueSorted } from '../utils/format.js';
import { can } from '../utils/permissions.js';
import { isCatalogVehicle, shipMatches, sortShips } from '../utils/ships.js';
import { routes } from '../config/routes.js';
import { routeClick } from '../utils/navigation.js';

/** Pagina de catalogo de naves con filtros y sincronizacion protegida. */
export function ShipsPage({ currentUser, navigate }) {
  const [ships, setShips] = useState([]);
  const [status, setStatus] = useState('Cargando catalogo local...');
  const [syncing, setSyncing] = useState(false);
  const [filters, setFilters] = useState({ search: '', manufacturer: '', type: '', role: '', sort: 'size' });
  useEffect(() => { requestJson('/api/vehicles').then((payload) => { setShips((payload.vehicles || []).filter(isCatalogVehicle)); setStatus(payload.warnings?.length ? 'Naves cargadas desde ' + payload.source + '. Algunos precios no estan disponibles temporalmente.' : 'Datos cargados desde ' + payload.source + '.'); }).catch((error) => setStatus(error.message.includes('EACCES') ? 'No se pudo acceder a UEX desde este entorno. Abre la web con npm run dev desde tu terminal local.' : 'No se pudo cargar el catalogo local: ' + error.message)); }, []);
  async function syncVehicles() { setSyncing(true); setStatus('Sincronizando UEX y Star Citizen Wiki con la base de datos local...'); try { const payload = await requestJson('/api/vehicles/sync', { method: 'POST' }); setShips((payload.vehicles || []).filter(isCatalogVehicle)); setStatus(payload.warnings?.length ? 'Base de datos actualizada. Algunas naves no tienen detalles Wiki completos.' : 'Base de datos actualizada con UEX y datos Wiki.'); } catch (error) { setStatus('No se pudo sincronizar el catalogo: ' + error.message); } finally { setSyncing(false); } }
  const catalogShips = ships.filter(isCatalogVehicle);
  const manufacturers = uniqueSorted(catalogShips.map((ship) => ship.manufacturer).filter(Boolean));
  const roles = uniqueSorted(catalogShips.flatMap((ship) => ship.tags || []));
  const visibleShips = sortShips(catalogShips.filter((ship) => shipMatches(ship, filters)), filters.sort);
  return <main className="container ships-shell"><section className="ships-toolbar panel"><div className="ships-toolbar-header"><div><span className="section-label">Busqueda</span><h2>Filtra el catalogo</h2><p>{status}</p></div><div className="ships-toolbar-actions"><span className="ships-count">{ships.length ? visibleShips.length + ' / ' + ships.length : 'Cargando...'}</span>{can(currentUser, 'ships.sync') && <button className="action-btn" type="button" onClick={syncVehicles} disabled={syncing}>{syncing ? 'Sincronizando...' : 'Sincronizar datos'}</button>}</div></div><div className="ships-controls"><ShipInput label="Buscar" value={filters.search} onChange={(value) => setFilters({ ...filters, search: value })} /><ShipSelect label="Fabricante" value={filters.manufacturer} values={manufacturers} onChange={(value) => setFilters({ ...filters, manufacturer: value })} /><ShipSelect label="Tipo" value={filters.type} values={[[ 'spaceship','Naves'],['ground','Terrestres'],['quantum','Quantum'],['concept','Concept']]} onChange={(value) => setFilters({ ...filters, type: value })} /><ShipSelect label="Rol" value={filters.role} values={roles} onChange={(value) => setFilters({ ...filters, role: value })} /><ShipSelect label="Orden" value={filters.sort} values={[[ 'size','Tamano'],['name','Nombre'],['pledge','Precio pledge'],['purchase','Compra in-game'],['rental','Alquiler'],['cargo','SCU']]} onChange={(value) => setFilters({ ...filters, sort: value })} /></div></section><section className={`ships-status ${visibleShips.length ? 'hidden' : ''}`}>{visibleShips.length ? '' : status}</section><section className="ships-grid">{visibleShips.map((ship) => <ShipCard key={ship.id} ship={ship} navigate={navigate} />)}</section></main>;
}

/** Campo de busqueda del catalogo. */
function ShipInput({ label, value, onChange }) { return <label>{label}<input type="search" value={value} onChange={(event) => onChange(event.target.value)} placeholder="Nombre, fabricante, rol..." /></label>; }

/** Selector reutilizable para filtros del catalogo. */
function ShipSelect({ label, value, values, onChange }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Todos</option>{values.map((item) => { const optionValue = Array.isArray(item) ? item[0] : item; const optionLabel = Array.isArray(item) ? item[1] : item; return <option key={optionValue} value={optionValue}>{optionLabel}</option>; })}</select></label>; }

/** Tarjeta visual de una nave, con fallback de imagen. */
function ShipCard({ ship, navigate }) { const [imageIndex, setImageIndex] = useState(0); const rawImages = ship.imageCandidates?.length ? ship.imageCandidates : [ship.photoProxy, ship.photo, ship.wikiImageProxy].filter(Boolean); const images = rawImages; const currentImage = images[imageIndex]; const detailPath = `${routes.ships}/${ship.id}-${slugify(ship.name)}`; return <article className="ship-card"><a className="ship-card-link" href={detailPath} onClick={(event) => routeClick(event, detailPath, navigate)}><div className="ship-image">{currentImage ? <img src={currentImage} width="1600" height="900" alt={ship.name} loading="lazy" onError={() => setImageIndex((index) => index + 1)} /> : <div className="ship-image-placeholder">SC</div>}</div><div className="ship-card-body"><div className="ship-title-row"><div><span>{ship.manufacturer}</span><h3>{ship.name}</h3></div><strong>{ship.padType}</strong></div><div className="ship-tags">{ship.tags?.slice(0, 4).map((tag) => <span key={tag}>{tag}</span>) || <span>Sin rol</span>}</div><dl className="ship-specs"><div><dt>Pledge</dt><dd>{money(ship.pledge?.price, ship.pledge?.currency || 'USD')}</dd></div><div><dt>Compra</dt><dd>{money(ship.purchase?.price)}</dd></div><div><dt>Alquiler</dt><dd>{money(ship.rental?.price)}</dd></div><div><dt>Carga</dt><dd>{ship.scu ? ship.scu + ' SCU' : 'N/D'}</dd></div><div><dt>Tripulacion</dt><dd>{ship.crew}</dd></div><div><dt>Longitud</dt><dd>{meters(ship.length)}</dd></div></dl><div className="ship-locations"><strong>Compra:</strong><span>{ship.purchase?.locations?.length ? ship.purchase.locations.join(', ') : 'Sin terminal conocido'}</span></div><div className="ship-locations"><strong>Alquiler:</strong><span>{ship.rental?.locations?.length ? ship.rental.locations.join(', ') : 'Sin terminal conocido'}</span></div><span className="ship-link">Ver ficha completa</span></div></a></article>; }
